services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: practice-db
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: akp@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
